declare const _default: {
    Container: string;
    Header: string;
    HeaderMonth: string;
    HeaderYear: string;
    HeaderYearsRange: string;
    Days: string;
    Day: string;
    PrevButton: string;
    NextButton: string;
    HeaderText: string;
    Body: string;
    BodyDays: string;
    BodyMonths: string;
    BodyYears: string;
    Cells: string;
    Cell: string;
    DayCell: string;
    MonthCell: string;
    YearCell: string;
    ValidDate: string;
    InvalidDate: string;
    DayBelongCurrentMonth: string;
    CurrentDate: string;
    SelectedDate: string;
    BetweenRange: string;
    BetweenSelectedRange: string;
    UnderMinRange: string;
    OverMaxRange: string;
    InvalidRangeDate: string;
    StartRangeDate: string;
    EndRangeDate: string;
    MouseOverEndRange: string;
};
export default _default;
